### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ammargilani** [marco-celoria/PLM4Muts#1]
Hi, as the repo has no license, I was wondering if it could be used commercially? Thanks!

**Comment by ammargilani** [comment]
Thanks for providing the license info. I would like to know if the requirements for all licenses need to be satisfied or if we can choose one. Thanks!

**Comment by marco-celoria** [comment]
Hi, actually the work is licensed under multiple licences.

Since there are many files, here you can find a brief summary. 
- All original source code and scripts are licensed under AGPL-3.0-or-later.
- All documentation, data, images are licensed under CC-BY-4.0.
- Some configuration files (.gitignore, requirements.txt, REUSE.toml, reuse.spdx) are licensed under CC0-1.0.
- Some code (preprocess_data/scripts/reformat.pl) borrowed from the HHsuite version 3.0.0 is licensed under GPL-3.0-or-later.

For more accurate information, you can either check the REUSE.toml file or the SPDX License List reuse.spdx or feel free to ask.

Thanks!
